import json, os
_SRC = json.load(open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "strings.json"), encoding="utf8"))
T = {
0: "Nea Moudania · Chalkidiki",
1: "Praxis für Gastroenterologie & Hepatologie · Endoskopiezentrum",
2: "Mit dem Anspruch auf ganzheitliche Betreuung und Hingabe heißen wir Sie in unserer gastroenterologisch-hepatologischen Praxis herzlich willkommen.",
3: "Termin vereinbaren",
4: "Direkt mit dem Arzt sprechen",
5: "Willkommen",
6: "Moderne, gut erreichbare medizinische Versorgung auf Chalkidiki",
7: "In unseren Räumen bieten wir hochwertige, moderne und gut zugängliche Gesundheitsleistungen an, die für die Region Chalkidiki innovativ sind und sich unmittelbar mit dem Angebot städtischer Zentren oder des Auslands messen können.",
8: "In unserer Praxis befindet sich ein voll ausgestattetes Endoskopiezentrum mit Geräten der neuesten Generation, das ein breites Spektrum an endoskopischen Untersuchungen und Eingriffen abdeckt.",
9: "Unser Ziel ist es, diese Leistungen den Menschen auf Chalkidiki – Einheimischen wie Gästen – schnell, unkompliziert und auf wissenschaftlich fundierter Grundlage anzubieten, individuell auf jeden Patienten abgestimmt.",
10: "Klinische Untersuchung",
11: "Ausführliche Anamnese und klinische Untersuchung, bei Bedarf mit Point-of-Care-Ultraschall (POCUS).",
12: "Magenspiegelung",
13: "Detaillierte Untersuchung von Speiseröhre, Magen und Zwölffingerdarm, mit intravenöser Sedierung und kontinuierlicher Überwachung.",
14: "Darmspiegelung & Polypenabtragung",
15: "Untersuchung des gesamten Dickdarms, Vorsorge und Abtragung von Polypen.",
16: "Darmultraschall",
17: "Nicht-invasive Beurteilung des Darms ohne Strahlenbelastung, bei Morbus Crohn und Colitis ulcerosa.",
18: "Leber-Elastografie",
19: "Shear-Wave-Elastografie zur nicht-invasiven Einschätzung der Leberfibrose.",
20: "Netzwerk von Kooperationspartnern",
21: "Rechtzeitige Überweisung und Weiterbetreuung bei ERCP, EUS, Manometrie und anderen spezialisierten Eingriffen.",
22: "Leistungen",
23: "Was wir anbieten",
24: "Alle Leistungen",
25: "Unser Ansatz",
26: "Sicherheit, Komfort und Qualität bei jeder Untersuchung",
27: "Sicherheit, Betreuung und Komfort der Patienten in jeder Phase der Untersuchung haben für unser Team oberste Priorität. Mit Professionalität, Diskretion und menschlicher Zuwendung möchten wir erreichen, dass sich jeder Patient in einem sicheren und gut organisierten Umfeld aufgehoben fühlt.",
28: "Den Arzt kennenlernen",
29: "Moderne intravenöse Sedierung für ein angenehmes und schmerzfreies Erlebnis",
30: "Kontinuierliche Überwachung der Vitalwerte: Monitor, Pulsoxymetrie, Kapnografie",
31: "Endoskope der neuesten Generation für hochwertige Bildgebung",
32: "Spezialisiertes Pflegepersonal mit langjähriger Erfahrung",
33: "Ausführliche Besprechung der Befunde und Möglichkeit, die Bilder anzusehen",
34: "Vereinbaren Sie Ihren Termin",
35: "Die Praxis arbeitet ausschließlich nach Terminvereinbarung, damit für jeden Patienten die nötige Zeit zur Verfügung steht und unnötige Wartezeiten sowie volle Wartezimmer vermieden werden.",
36: "Startseite",
37: "<em>Hier das Foto des Arztes einfügen (Bild-Widget → Bild auswählen).</em>",
38: "Der Arzt",
39: "Unser Weg",
40: "Aufgewachsen in Nea Moudania auf Chalkidiki, mit familiären Wurzeln in Simantra und Nea Triglia, begann der Arzt 2008 sein Medizinstudium an der Medizinischen Fakultät der Aristoteles-Universität Thessaloniki.",
41: "Das Studium wurde 2014 nach sechs Jahren abgeschlossen. Nach dem Militärdienst als Arzt in der 31. Brigade in Evros arbeitete der Arzt vier Jahre lang am Allgemeinen Krankenhaus Chalkidiki und wurde dort in der Inneren Medizin ausgebildet.",
42: "Die Weiterbildung in Gastroenterologie erfolgte am Allgemeinen Krankenhaus Thessaloniki „G. Papanikolaou“; die Facharztausbildung wurde nach vier Jahren Ausbildung und klinischer Tätigkeit in der Gastroenterologischen Klinik abgeschlossen.",
43: "Es folgte eine Fortbildung in Deutschland mit Spezialisierung auf den Darmultraschall am Universitätsklinikum Carl Gustav Carus in Dresden, die die klinische und diagnostische Erfahrung weiter vertiefte.",
44: "2024 kehrte der Arzt nach Chalkidiki zurück, in die Region, in der der Arzt aufgewachsen ist, mit dem Ziel, die über die Jahre gewonnene Erfahrung und das erworbene Wissen in die Heimat zu tragen. Aus dieser Vision entstand in Nea Moudania eine moderne gastroenterologisch-hepatologische Praxis mit Endoskopiezentrum, die den Patienten, die moderne Medizin und eine hochwertige medizinische Versorgung in unserer Region in den Mittelpunkt stellt.",
45: "Ausbildung",
46: "Stationen des beruflichen Werdegangs",
47: "2008–2014 · Medizinische Fakultät der Aristoteles-Universität Thessaloniki",
48: "Militärdienst als Arzt · 31. Brigade, Evros",
49: "4 Jahre · Innere Medizin, Allgemeines Krankenhaus Chalkidiki",
50: "4 Jahre · Facharztausbildung Gastroenterologie, Allgemeines Krankenhaus Thessaloniki „G. Papanikolaou“",
51: "Fortbildung im Darmultraschall · Universitätsklinikum Carl Gustav Carus, Dresden",
52: "Ausbildungsprogramm der International Bowel Ultrasound Group (IBUS)",
53: "2024 · Rückkehr nach Chalkidiki und Gründung der Praxis in Nea Moudania",
54: "Das Team",
55: "In jeder Phase an Ihrer Seite",
56: "Das Pflegepersonal unseres Zentrums besteht aus Fachkräften mit langjähriger Erfahrung in medizinischen Einrichtungen in Griechenland und im Ausland sowie mit spezieller Erfahrung in der Gastroenterologie und bei endoskopischen Eingriffen.",
57: "Sicherheit, Betreuung und Komfort der Patienten in jeder Phase der Untersuchung haben für unser Team oberste Priorität. Von der Vorbereitung und dem Empfang über die Überwachung während der Endoskopie bis zur Erholung nach der Sedierung steht das Pflegepersonal dem Patienten stets zur Seite.",
58: "Die enge Zusammenarbeit zwischen Arzt und Pflegepersonal trägt zu einem reibungslosen und sicheren Ablauf der endoskopischen Untersuchungen bei, mit kontinuierlicher Überwachung und sofortiger Reaktion auf die Bedürfnisse jedes Patienten.",
59: "Mit Professionalität, Diskretion und menschlicher Zuwendung möchten wir erreichen, dass sich jeder Patient in einem sicheren und gut organisierten Umfeld aufgehoben fühlt, in dem die Qualität der medizinischen Versorgung mit Respekt vor den persönlichen Bedürfnissen verbunden ist.",
60: "Der Arzt & das Team",
61: "Darmspiegelung",
62: "Polypenabtragung",
63: "Leistung",
64: "Klinische Untersuchung – Termin",
65: "Ausgehend von einer ausführlichen Anamnese und der klinischen Untersuchung können wir akute, subakute und chronische Erkrankungen des Magen-Darm-Trakts und der Leber abklären.",
66: "Die klinische Untersuchung wird bei Bedarf durch einen Ultraschall am Behandlungsort (Point-of-Care Ultrasound – POCUS) ergänzt, der eine unmittelbare zusätzliche Beurteilung ermöglicht.",
67: "Unsere Praxis arbeitet <strong>ausschließlich nach Terminvereinbarung</strong>, damit für jeden Patienten die nötige Zeit zur Verfügung steht und unnötige Wartezeiten sowie volle Wartezimmer vermieden werden.",
68: "Was Sie mitbringen sollten",
69: "<p>Für eine bestmögliche und vollständige Beurteilung ist es hilfreich, wenn Patienten zum Termin aktuelle Untersuchungsergebnisse mitbringen, etwa Blutwerte und bildgebende Befunde, sowie die Ergebnisse früherer endoskopischer Untersuchungen.</p><p>Zur Abwicklung bitten wir Sie, Ihre AMKA (griechische Sozialversicherungsnummer) oder, falls vorhanden, Ihre Europäische Krankenversicherungskarte (EHIC) mitzubringen.</p>",
70: "Moderne intravenöse Sedierung, für ein angenehmes und schmerzfreies Erlebnis des Patienten.",
71: "Kontinuierliche Überwachung der Vitalwerte während der gesamten Untersuchung mit Monitor, Pulsoxymetrie und Kapnografie.",
72: "Endoskope der neuesten Generation für hochwertige Bildgebung und eine detaillierte Untersuchung des oberen Verdauungstrakts.",
73: "In unserem Zentrum wird die Endoskopie des oberen Verdauungstrakts mit modernen Methoden durchgeführt, mit Schwerpunkt auf Sicherheit, Komfort und Qualität der Untersuchung.",
74: "<strong>Die Untersuchung erfolgt nach folgenden Standards:</strong>",
75: "Die Magenspiegelung ermöglicht eine detaillierte Untersuchung von Speiseröhre, Magen und Zwölffingerdarm. Während der Untersuchung können Proben zum Nachweis von <em>Helicobacter pylori</em> sowie bei Bedarf Biopsien der Schleimhaut entnommen werden.",
76: "Nach der Untersuchung und dem Aufwachen aus der Sedierung bespricht der Arzt die Befunde ausführlich mit dem Patienten. Der Patient kann außerdem die während der Untersuchung aufgenommenen Bilder ansehen.",
77: "Vorbereitung auf die Magenspiegelung",
78: "<p>Für die Magenspiegelung müssen Sie ab dem Morgen des Untersuchungstages nüchtern bleiben (keine feste Nahrung). Flüssigkeiten sollten mindestens zwei Stunden vor der Untersuchung nicht mehr getrunken werden, gemäß den Anweisungen, die Sie bei der Terminvereinbarung erhalten.</p>",
79: "Moderne intravenöse Sedierung, für ein möglichst angenehmes und schmerzfreies Erlebnis des Patienten.",
80: "Endoskope der neuesten Generation für hochwertige Bildgebung und eine detaillierte Untersuchung des Dickdarms.",
81: "In unserem Zentrum wird die Darmspiegelung mit modernen Methoden durchgeführt, mit Schwerpunkt auf Sicherheit, Komfort und Qualität der Untersuchung.",
82: "Die Darmspiegelung ermöglicht eine detaillierte Untersuchung des gesamten Dickdarms und des letzten Abschnitts des Dünndarms mit unmittelbarer Beurteilung der Schleimhaut. Während der Untersuchung können Biopsien aus auffälligen Bereichen entnommen und bei Bedarf Polypen abgetragen werden.",
83: "Die Darmspiegelung ist eine wichtige Untersuchung, sowohl zur Abklärung von Beschwerden und zur Überwachung bekannter Darmerkrankungen als auch zur Vorsorge und Früherkennung von Krebsvorstufen und Darmkrebs.",
84: "Nach der Untersuchung und dem Aufwachen aus der Sedierung bespricht der Arzt die Befunde ausführlich mit dem Patienten. Der Patient kann außerdem die aufgenommenen Bilder ansehen und wird über etwaige Biopsien oder andere durchgeführte endoskopische Eingriffe informiert.",
85: "Vorbereitung auf die Darmspiegelung",
86: "<p>Eine gute Darmvorbereitung ist die Voraussetzung für eine sichere und aussagekräftige Darmspiegelung. Sie umfasst eine spezielle Diät und die Einnahme eines Abführmittels gemäß den individuellen Anweisungen, die Sie vor der Untersuchung erhalten.</p><p>Die genaue Einhaltung der Vorbereitungsanweisungen ist besonders wichtig, denn ein gut gereinigter Darm ermöglicht die bestmögliche Beurteilung der Schleimhaut und verringert die Wahrscheinlichkeit, kleine Veränderungen oder Polypen zu übersehen.</p><p>Am Untersuchungstag sind die Anweisungen zu Nüchternheit und Flüssigkeitsaufnahme sowie etwaige besondere Anweisungen zur Medikation zu beachten, insbesondere bei Patienten, die Gerinnungshemmer oder Diabetesmedikamente einnehmen.</p>",
87: "Bei einer Darmspiegelung können Polypen im Dickdarm entdeckt werden. Die meisten Polypen sind gutartig, einige können sich jedoch im Laufe der Zeit zu Krebsvorstufen und seltener zu Darmkrebs entwickeln.",
88: "In unserem Zentrum ist die Polypenabtragung bei den meisten Polypen möglich, entweder während der ersten Darmspiegelung oder in einem zweiten Termin, abhängig von den Merkmalen des Polypen und mit Blick auf Komfort und vor allem die Sicherheit des Patienten.",
89: "Die Polypenabtragung (Polypektomie) ist die endoskopische Entfernung von Polypen während der Darmspiegelung. Je nach Größe, Form und Lage des Polypen wird die geeignete endoskopische Technik für eine sichere und vollständige Entfernung gewählt.",
90: "Das entfernte Gewebe wird zur histologischen Untersuchung eingesendet. Sie ermöglicht die genaue Bestimmung von Art und Eigenschaften des Polypen und trägt zur Festlegung der weiteren Nachsorge bei.",
91: "Die Polypenabtragung ist ein wichtiger Bestandteil der Darmkrebsvorsorge, da die frühzeitige Erkennung und Entfernung von Krebsvorstufen deren Entwicklung zu einem bösartigen Tumor verhindern kann.",
92: "Nach der Untersuchung bespricht der Arzt mit dem Patienten ausführlich die Befunde, die entdeckten und entfernten Polypen sowie die Notwendigkeit weiterer Kontrollen, abhängig von den Ergebnissen der histologischen Untersuchung.",
93: "Der Darmultraschall (Intestinal Ultrasound – IUS) ist eine moderne, nicht-invasive und strahlungsfreie Methode zur unmittelbaren Beurteilung des Darms.",
94: "Mit speziellem Ultraschallgerät lässt sich die Darmwand detailliert darstellen und das Vorhandensein sowie das Ausmaß einer Entzündung beurteilen. Besonders nützlich ist er bei der Diagnose und Verlaufskontrolle chronisch-entzündlicher Darmerkrankungen wie Morbus Crohn und Colitis ulcerosa.",
95: "Einer der wichtigsten Vorteile der Methode ist, dass sie unmittelbar in der Praxis durchgeführt wird, ohne Strahlung und in den meisten Fällen ohne besondere Vorbereitung. Sie kann daher bei Bedarf wiederholt werden und ermöglicht eine engmaschige Kontrolle des Krankheitsverlaufs und des Ansprechens auf die Therapie.",
96: "Der Darmultraschall kann ergänzend zur klinischen Untersuchung, zu Laboruntersuchungen und zur Endoskopie eingesetzt werden und liefert eine unmittelbare und objektive Beurteilung des Darmzustands.",
97: "Spezialisierung auf den Darmultraschall – IBUS",
98: "Der Arzt hat das vollständige Ausbildungsprogramm der International Bowel Ultrasound Group (IBUS) absolviert, einer internationalen wissenschaftlichen Organisation, die sich der Ausbildung, der Forschung und der klinischen Anwendung des Darmultraschalls widmet.",
99: "Die Ausbildung umfasst theoretische und praktische Schulungen, umfangreiches praktisches Training (Hands-on) in einem spezialisierten Zentrum sowie fortgeschrittene Schulungen zu den modernen Anwendungen des Darmultraschalls, mit Schwerpunkt auf der Diagnose und Verlaufskontrolle chronisch-entzündlicher Darmerkrankungen.",
100: "Zudem gehörte der Arzt zu den ersten Mitgliedern der IBUS in Griechenland und war von Anfang an an der Entwicklung und Verbreitung der Methode im Land beteiligt.",
101: "Diese spezialisierte Ausbildung und Erfahrung ermöglichen den Einsatz des Darmultraschalls in der täglichen klinischen Praxis, insbesondere für die objektive und wiederholbare Beurteilung von Patienten mit Morbus Crohn und Colitis ulcerosa sowie mit anderen Darmerkrankungen.",
102: "Shear-Wave-Elastografie der Leber",
103: "Die Shear-Wave-Elastografie (SWE) ist eine moderne, nicht-invasive Ultraschallmethode zur Bestimmung der Gewebesteifigkeit der Leber und damit zur nicht-invasiven Beurteilung des Grades der Leberfibrose.",
104: "In unserem Zentrum wird diese Untersuchung im Rahmen der hepatologischen Abklärung und Verlaufskontrolle angeboten, da die Elastografie ein unverzichtbares Hilfsmittel der modernen Hepatologie ist.",
105: "Bei der Untersuchung erzeugen und erfassen spezielle Ultraschallwellen Scherwellen (Shear Waves) im Lebergewebe. Ihre Ausbreitungsgeschwindigkeit wird zur Berechnung der Lebersteifigkeit verwendet und liefert quantitative Informationen, die zur Stadieneinteilung der Fibrose beitragen können.",
106: "Die Methode ist schmerzlos, schnell und nicht-invasiv, ohne Strahlung, und kann im Rahmen der Ultraschalluntersuchung der Leber durchgeführt werden. Sie ist ein nützliches Instrument zur Beurteilung und Verlaufskontrolle von Patienten mit chronischer Lebererkrankung, wie der metabolisch assoziierten steatotischen Lebererkrankung (MASLD), viraler Hepatitis und anderen chronischen Lebererkrankungen.",
107: "Die Elastografie ersetzt weder die klinische Beurteilung noch Laboruntersuchungen, ist aber ein wichtiger Bestandteil der modernen nicht-invasiven Beurteilung der Leberfibrose und kann helfen, Patienten mit erhöhtem Risiko für eine fortgeschrittene Fibrose zu erkennen.",
108: "Die Untersuchung kann bei Bedarf im Verlauf wiederholt werden und ermöglicht so, zusammen mit den übrigen klinischen und Laborwerten, die Beurteilung des Verlaufs der Lebererkrankung.",
109: "Moderne diagnostische und endoskopische Untersuchungen mit Schwerpunkt auf Sicherheit, Komfort und Qualität.",
110: "Nachfolgend sind beispielhaft einige der häufigsten Erkrankungen des Magen-Darm-Trakts und der Leber aufgeführt, die in unserem Zentrum behandelt und überwacht werden.",
111: "Magen-Darm-Trakt",
112: "Gastroösophageale Refluxkrankheit",
113: "Gastritis",
114: "Funktionelle Dyspepsie",
115: "Reizdarmsyndrom",
116: "Abklärung von chronischem Durchfall",
117: "Verstopfung",
118: "Chronisch-entzündliche Darmerkrankungen: Colitis ulcerosa, Morbus Crohn",
119: "Divertikulose und Divertikulitis",
120: "Hämorrhoidalleiden und Analfissur",
121: "Zöliakie",
122: "Leber, Gallenwege und Bauchspeicheldrüse",
123: "Chronische Virushepatitis",
124: "Abklärung erhöhter Transaminasen",
125: "Metabolisch assoziierte steatotische Lebererkrankung (MASLD)",
126: "Leberzirrhose",
127: "Aszites",
128: "Autoimmunerkrankungen der Leber und der Gallenwege",
129: "Erkrankungen der Gallenwege und der Bauchspeicheldrüse",
130: "Ganzheitliche Betreuung, wenn weitere Abklärung nötig ist",
131: "Unser Zentrum verfügt über ein gut organisiertes Netzwerk erfahrener und spezialisierter Kooperationspartner, um Patienten ganzheitlich zu behandeln und zu betreuen, wenn eine weitere spezialisierte Abklärung oder therapeutische Intervention erforderlich ist.",
132: "Ziel des Netzwerks ist die rechtzeitige Überweisung, die Wahl des geeigneten Therapieansatzes und die Kontinuität der Patientenbetreuung in Zusammenarbeit mit den jeweiligen Fachärzten.",
133: "Durch die Zusammenarbeit mit Fachärzten und spezialisierten Zentren sind Überweisung und koordinierte Behandlung bei einem breiten Spektrum gastroenterologischer Erkrankungen und spezialisierter Eingriffe möglich, wie zum Beispiel:",
134: "ERCP und therapeutische Eingriffe an Gallenwegen und Bauchspeicheldrüse",
135: "Endoskopischer Ultraschall (EUS)",
136: "Manometrie und Impedanzmessung der Speiseröhre zur Abklärung von Motilitätsstörungen und gastroösophagealem Reflux",
137: "Interventionelle und fortgeschrittene Endoskopie",
138: "Anlage einer Gastrostomie (PEG)",
139: "Onkologische Behandlung von Erkrankungen des Verdauungstrakts",
140: "Chirurgische Behandlung von Erkrankungen des Verdauungssystems",
141: "Erkrankungen",
142: "Erkrankungen, die wir behandeln",
143: "Erkrankungen & Netzwerk von Kooperationspartnern",
144: "Kontakt",
145: "Nehmen Sie Kontakt auf",
146: "Rufen Sie uns an, um einen Termin zu vereinbaren: <strong>%s</strong>, oder sprechen Sie direkt mit dem Arzt unter <strong>%s</strong>.",
147: "Termin",
148: "Der Arzt",
149: "Route in Google Maps",
150: "Nea Moudania, Chalkidiki, Griechenland",
151: "Das sagen unsere Patienten",
152: "Lesen Sie die Bewertungen unserer Patienten bei Google oder hinterlassen Sie Ihre eigene.",
153: "Google-Bewertungen ansehen",
154: "Anruf",
155: "Nea Moudania, Chalkidiki",
156: "Terminvereinbarung",
157: "Die Informationen auf dieser Website dienen der allgemeinen Information und ersetzen keine ärztliche Untersuchung oder Beratung.",
}
assert len(T) == len(_SRC) == 158 and set(T) == set(range(158))
D = {_SRC[i]: T[i] for i in T}
