import json, os
_SRC = json.load(open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "strings.json"), encoding="utf8"))
T = {
0: "Nea Moudania · Chalkidiki",
1: "Gastroenterology – Hepatology Clinic & Endoscopy Center",
2: "With a spirit of complete care and dedication, we welcome you to our Gastroenterology – Hepatology Clinic.",
3: "Book an appointment",
4: "Speak directly with the doctor",
5: "Welcome",
6: "Modern, accessible healthcare services in Chalkidiki",
7: "Our facility offers high-quality, modern and accessible healthcare services, innovative for the region of Chalkidiki and directly comparable to those of major urban centers or centers abroad.",
8: "Our clinic houses a fully equipped endoscopy unit with state-of-the-art systems, covering a wide range of endoscopic examinations and procedures.",
9: "Our goal is to offer these services to the people of Chalkidiki, residents and visitors alike, with promptness, easy access and scientific rigor, personalized for each patient.",
10: "Clinical examination",
11: "Full medical history and clinical examination, with point-of-care ultrasound (POCUS) where needed.",
12: "Gastroscopy",
13: "Detailed examination of the esophagus, stomach and duodenum, with intravenous sedation and continuous monitoring.",
14: "Colonoscopy & Polypectomy",
15: "Examination of the entire large intestine, prevention and removal of polyps.",
16: "Intestinal ultrasound",
17: "Non-invasive assessment of the bowel, without radiation, for Crohn's disease and ulcerative colitis.",
18: "Liver elastography",
19: "Shear Wave Elastography for non-invasive assessment of liver fibrosis.",
20: "Network of collaborators",
21: "Timely referral and continuity of care for ERCP, EUS, manometry and other specialized procedures.",
22: "Services",
23: "What we offer",
24: "All services",
25: "Our approach",
26: "Safety, comfort and quality in every examination",
27: "The safety, care and comfort of the patient at every stage of the examination is our team's top priority. With professionalism, discretion and a human approach, our aim is for every patient to feel they are in a safe and well-organized environment.",
28: "Meet the doctor",
29: "Modern intravenous sedation for a comfortable and painless experience",
30: "Continuous monitoring of vital signs: monitor, oximetry, capnography",
31: "Latest-generation endoscopes for high-quality imaging",
32: "Specialized nursing staff with long-standing experience",
33: "Detailed explanation of the findings and the option to view the images",
34: "Book your appointment",
35: "The clinic operates by appointment only, so that every patient has the time they need and unnecessary waiting and crowding in the waiting room are avoided.",
36: "Home",
37: "<em>Add the doctor's photo here (Image widget → Choose Image).</em>",
38: "The Doctor",
39: "Our journey",
40: "Raised in Nea Moudania, Chalkidiki, with roots in Simantra and Nea Triglia, the doctor began studying at the School of Medicine of the Aristotle University of Thessaloniki in 2008.",
41: "Graduating in 2014 after six years of study, and following military service as a doctor with the 31st Brigade in Evros, the doctor worked for four years at the General Hospital of Chalkidiki, training in the Internal Medicine Department.",
42: "Training in Gastroenterology continued at the General Hospital of Thessaloniki “G. Papanikolaou”, where the specialty was completed after four years of training and clinical work in the Gastroenterology Department.",
43: "Postgraduate training in Germany followed, with a specialization in intestinal ultrasound at the Carl Gustav Carus University Hospital in Dresden, further broadening clinical and diagnostic experience.",
44: "In 2024 the doctor returned to Chalkidiki, the region where they grew up, with the aim of bringing the experience and knowledge gained over the years back home. With this vision, a modern Gastroenterology – Hepatology Clinic and Endoscopy Center was created in Nea Moudania, focused on the patient, modern medicine and high-quality healthcare services for our community.",
45: "Education",
46: "Career milestones",
47: "2008–2014 · School of Medicine, Aristotle University of Thessaloniki",
48: "Military service as a doctor · 31st Brigade, Evros",
49: "4 years · Internal Medicine Department, General Hospital of Chalkidiki",
50: "4 years · Gastroenterology residency, General Hospital of Thessaloniki “G. Papanikolaou”",
51: "Postgraduate training in intestinal ultrasound · Carl Gustav Carus University Hospital, Dresden",
52: "Training program of the International Bowel Ultrasound Group (IBUS)",
53: "2024 · Return to Chalkidiki and founding of the clinic in Nea Moudania",
54: "Our staff",
55: "By your side at every stage",
56: "The nursing staff of our center consists of healthcare professionals with long-standing experience in healthcare institutions in Greece and abroad, as well as specialized experience in gastroenterology and endoscopic procedures.",
57: "The safety, care and comfort of the patient at every stage of the examination is our team's top priority. From preparation and reception, through monitoring during the endoscopy, to recovery after sedation, the nursing staff is always at the patient's side.",
58: "Close cooperation between the doctor and the nursing staff ensures the smooth and safe performance of endoscopic examinations, with continuous monitoring and immediate response to each patient's needs.",
59: "With professionalism, discretion and a human approach, our aim is for every patient to feel they are in a safe and well-organized environment, where the quality of medical care is combined with respect for their personal needs.",
60: "The Doctor & the team",
61: "Colonoscopy",
62: "Polypectomy",
63: "Service",
64: "Clinical examination – Appointment",
65: "Starting with a full medical history and a clinical examination, we can investigate acute, subacute and chronic conditions of the gastrointestinal system and the liver.",
66: "The clinical examination is complemented, where necessary, by point-of-care ultrasound (POCUS), providing the possibility of immediate additional assessment.",
67: "Our clinic operates <strong>by appointment only</strong>, so that every patient has the time they need, and to avoid unnecessary waiting and crowding in the waiting room.",
68: "What to bring with you",
69: "<p>For the best and most complete assessment, it is useful for patients to bring to their appointment recent tests, such as blood tests and imaging studies, as well as the results of any previous endoscopic examinations.</p><p>To complete the process, please bring your AMKA (Greek social security number) or, if you have one, your European Health Insurance Card.</p>",
70: "Modern intravenous sedation, aiming for a comfortable and painless experience for the patient.",
71: "Continuous monitoring of vital signs throughout the examination, with monitor, oximetry and capnography.",
72: "Latest-generation endoscopes, for high-quality imaging and a detailed examination of the upper digestive tract.",
73: "Upper gastrointestinal endoscopy is performed at our center using modern methods, with an emphasis on safety, comfort and the quality of the examination.",
74: "<strong>The examination is performed to the following standards:</strong>",
75: "Gastroscopy allows a detailed examination of the esophagus, stomach and duodenum. During the examination, samples may be taken to test for <em>Helicobacter pylori</em>, as well as biopsies of the mucosa when necessary.",
76: "After the examination, once the patient has recovered from sedation, the doctor gives a detailed explanation of the findings. The patient can also view the images recorded during the examination.",
77: "Preparation for gastroscopy",
78: "<p>Gastroscopy requires fasting from solid food from the morning of the examination. Fluids must be stopped at least two hours before the examination, according to the instructions you will be given when scheduling your appointment.</p>",
79: "Modern intravenous sedation, aiming for a comfortable and as painless an experience as possible for the patient.",
80: "Latest-generation endoscopes, for high-quality imaging and a detailed examination of the large intestine.",
81: "Colonoscopy is performed at our center using modern methods, with an emphasis on safety, comfort and the quality of the examination.",
82: "Colonoscopy allows a detailed examination of the entire large intestine and the final part of the small intestine, with direct assessment of the mucosa. During the examination, biopsies can be taken from areas with abnormal findings, and polyps can be removed when necessary.",
83: "Colonoscopy is an important examination both for investigating symptoms and monitoring known bowel conditions, and for screening and early detection of precancerous lesions and colorectal cancer.",
84: "After the examination, once the patient has recovered from sedation, the doctor gives a detailed explanation of the findings. The patient can also view the images recorded during the examination and learn about any biopsies or other endoscopic procedures that were performed.",
85: "Preparation for colonoscopy",
86: "<p>Proper bowel preparation is an essential prerequisite for a safe and reliable colonoscopy. Preparation includes a special diet and a laxative preparation, following individualized instructions you will receive before the examination.</p><p>Following the preparation instructions exactly is especially important, since a well-cleansed bowel allows the best possible visualization of the mucosa and reduces the chance of missing small lesions or polyps.</p><p>On the day of the examination, the instructions on fasting and fluid intake must be followed, together with any special instructions regarding medication, especially for patients taking anticoagulants or diabetes medication.</p>",
87: "During colonoscopy, polyps may be found in the large intestine. Most polyps are benign, but some may, over time, develop into precancerous lesions and, more rarely, into colorectal cancer.",
88: "At our center, polypectomy is possible for most polyps, either during the initial colonoscopy or at a second session, depending on the characteristics of the polyp and guided by convenience and, above all, the safety of the patient.",
89: "Polypectomy is the endoscopic removal of polyps during colonoscopy. Depending on the size, shape and location of the polyp, the appropriate endoscopic technique is chosen for its safe and complete removal.",
90: "The removed tissue is sent for histological examination, which allows precise determination of the type and characteristics of the polyp and helps determine further follow-up.",
91: "Polypectomy is an important part of colorectal cancer prevention, since early detection and removal of precancerous polyps can prevent their progression to malignancy.",
92: "After the examination, the patient receives a detailed explanation from the doctor about the findings, the polyps that were found and removed, and the need for further follow-up, depending on the results of the histological examination.",
93: "Intestinal ultrasound (IUS) is a modern, non-invasive, radiation-free method for the immediate assessment of the bowel.",
94: "With specialized ultrasound equipment, the bowel wall can be imaged in detail and the presence and extent of inflammation can be assessed. It is particularly useful in the diagnosis and monitoring of inflammatory bowel diseases, such as Crohn's disease and ulcerative colitis.",
95: "One of the most important advantages of the method is that it is performed immediately at the clinic, without radiation and, in most cases, without any special preparation. It can therefore be repeated whenever necessary, allowing close monitoring of the course of the disease and the response to treatment.",
96: "Intestinal ultrasound can be used in addition to clinical examination, laboratory tests and endoscopy, providing an immediate and objective assessment of the condition of the bowel.",
97: "Specialization in intestinal ultrasound – IBUS",
98: "The doctor has completed the full training program of the International Bowel Ultrasound Group (IBUS), an international scientific organization active in the education, research and clinical application of intestinal ultrasound.",
99: "The training includes theoretical and practical instruction, extensive hands-on training at a specialized center, and advanced training in the modern applications of intestinal ultrasound, with an emphasis on the diagnosis and monitoring of inflammatory bowel diseases.",
100: "The doctor was also one of the first members of IBUS in Greece, taking part from the early stages in the development and dissemination of the method in the country.",
101: "This specialized training and experience make it possible to use intestinal ultrasound in everyday clinical practice, particularly for the objective and repeatable assessment of patients with Crohn's disease and ulcerative colitis, as well as other bowel conditions.",
102: "Shear Wave Liver Elastography",
103: "Shear Wave Elastography (SWE) is a modern, non-invasive ultrasound method for estimating the stiffness of the liver tissue and, by extension, for the non-invasive assessment of the degree of liver fibrosis.",
104: "Our center offers this examination as part of hepatological assessment and follow-up, since elastography is an essential tool of modern hepatology.",
105: "During the examination, special ultrasound waves generate and detect shear waves within the liver tissue. Their propagation speed is used to calculate liver stiffness, providing quantitative information that can help stage fibrosis.",
106: "The method is painless, quick and non-invasive, without radiation, and can be performed as part of the ultrasound examination of the liver. It is a useful tool in the assessment and monitoring of patients with chronic liver disease, such as metabolic dysfunction-associated steatotic liver disease (MASLD), viral hepatitis and other chronic liver conditions.",
107: "Elastography does not replace clinical assessment or laboratory tests, but is an important part of the modern non-invasive evaluation of liver fibrosis and can help identify patients at increased risk of advanced fibrosis.",
108: "The examination can be repeated during follow-up when necessary, allowing the course of liver disease to be assessed together with the other clinical and laboratory data.",
109: "Modern diagnostic and endoscopic examinations, with an emphasis on safety, comfort and quality.",
110: "Below are some of the most common conditions of the gastrointestinal system and the liver that are treated and monitored at our center.",
111: "Gastrointestinal system",
112: "Gastroesophageal reflux",
113: "Gastritis",
114: "Functional dyspepsia",
115: "Irritable bowel syndrome",
116: "Investigation of chronic diarrhea",
117: "Constipation",
118: "Inflammatory bowel diseases: ulcerative colitis, Crohn's disease",
119: "Diverticular disease and diverticulitis",
120: "Hemorrhoids and anal fissure",
121: "Celiac disease",
122: "Liver, bile ducts and pancreas",
123: "Chronic viral hepatitis",
124: "Investigation of elevated transaminases",
125: "Metabolic dysfunction-associated steatotic liver disease (MASLD)",
126: "Liver cirrhosis",
127: "Ascites",
128: "Autoimmune diseases of the liver and biliary system",
129: "Diseases of the bile ducts and pancreas",
130: "Complete care, when further investigation is needed",
131: "Our center has an organized network of experienced and specialized collaborators, aiming at the complete management and follow-up of patients when further specialized investigation or therapeutic intervention is required.",
132: "The aim of the network of collaborators is timely referral, the right choice of the appropriate therapeutic approach, and continuity of patient care, in cooperation with the respective specialist doctors.",
133: "Through cooperation with specialist doctors and centers, referral and coordinated management are possible for a wide range of gastroenterological conditions and specialized procedures, such as:",
134: "ERCP and therapeutic interventions of the bile ducts and pancreas",
135: "Endoscopic ultrasound (EUS)",
136: "Esophageal manometry and impedance testing, to investigate motility disorders and gastroesophageal reflux",
137: "Interventional and advanced endoscopy",
138: "Gastrostomy placement",
139: "Oncological management of digestive diseases",
140: "Surgical management of digestive system diseases",
141: "Conditions",
142: "Conditions we treat",
143: "Conditions & Network of collaborators",
144: "Contact",
145: "Get in touch",
146: "Contact us to book an appointment on <strong>%s</strong>, or call <strong>%s</strong> to speak directly with the doctor.",
147: "Appointments",
148: "The doctor",
149: "Directions on Google Maps",
150: "Nea Moudania, Chalkidiki, Greece",
151: "What our patients say",
152: "Read our patients' reviews on Google or leave your own.",
153: "See our Google reviews",
154: "Call",
155: "Nea Moudania, Chalkidiki",
156: "Appointments",
157: "The information on this website is for general information only and does not replace a medical examination or advice.",
}
assert len(T) == len(_SRC) == 158 and set(T) == set(range(158))
D = {_SRC[i]: T[i] for i in T}
